/* ============================================
   maze.js
   Renders the maze and runs the code generated by Blockly.

   HOW EXECUTION WORKS (important to understand for your
   Implementation write-up):
   1. Blockly.JavaScript.workspaceToCode() turns the blocks
      into a plain JS text string, e.g.:
         moveForward();
         moveForward();
         turnRight();
   2. We can't just eval() that and expect animation, because
      eval() runs instantly — the character would "teleport"
      instead of stepping visibly through the maze.
   3. So moveForward() and turnRight() don't move the character
      directly. Instead, they push an instruction onto a queue
      (actionQueue). This is sometimes called a "command pattern".
   4. Once the whole program has run (and the queue is full of
      instructions), we animate through the queue one instruction
      at a time using setInterval, updating the canvas each step.
   ============================================ */

const CELL_SIZE = 40;

// Direction is stored in degrees: 0 = facing right, 90 = down,
// 180 = left, 270 = up. Turning right adds 90 degrees.
const DIRECTION_VECTORS = {
  0: { dr: 0, dc: 1 },
  90: { dr: 1, dc: 0 },
  180: { dr: 0, dc: -1 },
  270: { dr: -1, dc: 0 },
};

let currentLevel = null;
let character = { row: 0, col: 0, direction: 0 };
let actionQueue = [];
let animationTimer = null;

function drawMaze(levelId) {
  currentLevel = LEVELS.find((l) => l.id === levelId);
  const canvas = document.getElementById("maze-canvas");
  const ctx = canvas.getContext("2d");
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  currentLevel.grid.forEach((row, rowIndex) => {
    row.forEach((cell, colIndex) => {
      const x = colIndex * CELL_SIZE;
      const y = rowIndex * CELL_SIZE;
      ctx.fillStyle = cell === 1 ? "#854F0B" : "#F5EFE6";
      ctx.fillRect(x, y, CELL_SIZE, CELL_SIZE);
      ctx.strokeStyle = "#D9CBB5";
      ctx.strokeRect(x, y, CELL_SIZE, CELL_SIZE);
    });
  });

  const goalX = currentLevel.goal.col * CELL_SIZE;
  const goalY = currentLevel.goal.row * CELL_SIZE;
  ctx.fillStyle = "#F2703C";
  ctx.beginPath();
  ctx.moveTo(goalX + CELL_SIZE / 2, goalY + 8);
  ctx.lineTo(goalX + CELL_SIZE - 10, goalY + CELL_SIZE / 4);
  ctx.lineTo(goalX + CELL_SIZE / 2, goalY + CELL_SIZE / 2);
  ctx.fill();
}

// Draws the maze walls/path fresh, then the character on top —
// this is what lets the character appear to "move" between frames.
function renderFrame() {
  drawMaze(currentLevel.id);

  const canvas = document.getElementById("maze-canvas");
  const ctx = canvas.getContext("2d");
  const x = character.col * CELL_SIZE + CELL_SIZE / 2;
  const y = character.row * CELL_SIZE + CELL_SIZE / 2;

  ctx.fillStyle = "#16A394";
  ctx.beginPath();
  ctx.arc(x, y, CELL_SIZE / 3, 0, Math.PI * 2);
  ctx.fill();

  // Small line showing which way the character is facing
  const vec = DIRECTION_VECTORS[character.direction];
  ctx.strokeStyle = "#04342C";
  ctx.lineWidth = 3;
  ctx.beginPath();
  ctx.moveTo(x, y);
  ctx.lineTo(x + vec.dc * 14, y + vec.dr * 14);
  ctx.stroke();
}

function drawCharacter(position) {
  character = { ...position, direction: 0 };
  renderFrame();
}

// These two functions are what the generated code calls.
// They do NOT move the character immediately — they just log
// an instruction. See the explanation at the top of this file.
function moveForward() {
  actionQueue.push({ type: "move" });
}
function turnRight() {
  actionQueue.push({ type: "turn" });
}

function setFeedback(text) {
  document.getElementById("feedback-text").textContent = text;
}

function runCode(generatedCode) {
  if (animationTimer) clearInterval(animationTimer);

  // Reset character to the level's start position before running
  character = { ...currentLevel.start, direction: 0 };
  actionQueue = [];
  renderFrame();
  setFeedback("Running...");

  // Populate the queue by actually running the generated code.
  // moveForward()/turnRight() below are the ones defined above,
  // so this just fills actionQueue — nothing moves yet.
  try {
    eval(generatedCode);
  } catch (err) {
    setFeedback("There's an error in your blocks: " + err.message);
    return;
  }

  let hitWall = false;

  animationTimer = setInterval(() => {
    if (actionQueue.length === 0) {
      clearInterval(animationTimer);
      const result = checkResult(character, currentLevel.goal);
      showResult(hitWall ? "fail" : result);
      return;
    }

    const action = actionQueue.shift();

    if (action.type === "turn") {
      character.direction = (character.direction + 90) % 360;
    } else if (action.type === "move") {
      const vec = DIRECTION_VECTORS[character.direction];
      const nextRow = character.row + vec.dr;
      const nextCol = character.col + vec.dc;
      const nextCell = currentLevel.grid[nextRow] && currentLevel.grid[nextRow][nextCol];

      if (nextCell === undefined || nextCell === 1) {
        // Walked into a wall or off the grid — stop early
        hitWall = true;
        actionQueue = [];
      } else {
        character.row = nextRow;
        character.col = nextCol;
      }
    }

    renderFrame();
  }, 500); // half a second per step — slow enough for a child to follow
}

function checkResult(position, goal) {
  return position.row === goal.row && position.col === goal.col ? "success" : "fail";
}

function showResult(result) {
  showScreen("result-screen");
  const icon = document.getElementById("result-icon");
  const title = document.getElementById("result-title");
  const stars = document.getElementById("result-stars");
  const nextBtn = document.getElementById("next-level-btn");

  if (result === "success") {
    icon.textContent = "🏆";
    title.textContent = "Level complete!";
    stars.textContent = "★ ★ ★";
    nextBtn.style.display = "inline-block";
  } else {
    icon.textContent = "😕";
    title.textContent = "Oops, try again!";
    stars.textContent = "";
    nextBtn.style.display = "none";
  }
}
