/* ============================================
   maze.js
   Renders the maze grid on the canvas and moves the
   character based on the code generated by Blockly.
   ============================================ */

const CELL_SIZE = 40; // pixels per grid cell — change this to resize the maze

// Draws the maze walls/paths for a given level onto #maze-canvas.
function drawMaze(levelId) {
  const level = LEVELS.find((l) => l.id === levelId);
  const canvas = document.getElementById("maze-canvas");
  const ctx = canvas.getContext("2d");

  // Clear anything previously drawn
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  // Loop over every cell in the grid and paint it
  level.grid.forEach((row, rowIndex) => {
    row.forEach((cell, colIndex) => {
      const x = colIndex * CELL_SIZE;
      const y = rowIndex * CELL_SIZE;

      ctx.fillStyle = cell === 1 ? "#854F0B" : "#F5EFE6"; // wall vs. open path
      ctx.fillRect(x, y, CELL_SIZE, CELL_SIZE);

      ctx.strokeStyle = "#D9CBB5";
      ctx.strokeRect(x, y, CELL_SIZE, CELL_SIZE);
    });
  });

  // Mark the goal with a small flag icon (drawn as a coloured triangle)
  const goalX = level.goal.col * CELL_SIZE;
  const goalY = level.goal.row * CELL_SIZE;
  ctx.fillStyle = "#F2703C";
  ctx.beginPath();
  ctx.moveTo(goalX + CELL_SIZE / 2, goalY + 8);
  ctx.lineTo(goalX + CELL_SIZE - 10, goalY + CELL_SIZE / 4);
  ctx.lineTo(goalX + CELL_SIZE / 2, goalY + CELL_SIZE / 2);
  ctx.fill();
}

// Draws the character (a simple circle) at a given grid position.
// position looks like { row: 1, col: 1 }
function drawCharacter(position) {
  const canvas = document.getElementById("maze-canvas");
  const ctx = canvas.getContext("2d");

  const x = position.col * CELL_SIZE + CELL_SIZE / 2;
  const y = position.row * CELL_SIZE + CELL_SIZE / 2;

  ctx.fillStyle = "#16A394";
  ctx.beginPath();
  ctx.arc(x, y, CELL_SIZE / 3, 0, Math.PI * 2);
  ctx.fill();
}

function runCode(generatedCode) {
  // TODO (next session): this will read the blocks the child placed
  // (via Blockly.JavaScript.workspaceToCode) and move the character
  // step by step, then call checkResult() to see if they reached the goal.
}

function checkResult(position, goal) {
  return position.row === goal.row && position.col === goal.col ? "success" : "fail";
}

