/* ============================================
   maze.js
   Renders the maze grid on the canvas and moves the
   character based on the code generated by Blockly.

   TODO (your implementation):
   - drawMaze(level): read LEVELS[level].grid and paint
     walls/open cells onto #maze-canvas using the Canvas API.
   - drawCharacter(position, direction): draw the character
     sprite/emoji at its current grid cell.
   - runCode(generatedCode): execute the JS generated by
     Blockly.JavaScript.workspaceToCode(), moving the character
     step by step (consider using small delays/animation so
     children can follow what's happening).
   - checkResult(position, goal): return "success" or "fail"
     depending on whether the character reached the goal.
   ============================================ */

function drawMaze(levelId) {
  // TODO: implement
}

function drawCharacter(position, direction) {
  // TODO: implement
}

function runCode(generatedCode) {
  // TODO: implement — this is the core "execution engine"
  // of the platform, worth documenting carefully in
  // Section 6 (Implementation) of the AE2 report.
}
